### PR TITLE
Require user to dismiss the interaction

### PR DESCRIPTION
**Pull request by cakenggt**
I often find that I don't know that I got new Github notifications when I was away from my desk, so making these require interaction makes them more like Slack's notifications.

### CODE REVIEW

**Comment by kierenj** [comment]
Yes please!

**Comment by gcochard** [comment]
I imagine quite a few people would be upset by this change. Can you make it a config option?

**Comment by sindresorhus** [comment]
Yes, needs to be opt-in.

**Comment by tooomm** [comment]
Is there a possibility to decide in a smart way?

Like if you are typing or moving the mouse then it will dismiss automatically after the normal time frame, because you are obviously sitting in front of the computer. If no input/movement is detected it'll stay.

**Comment by sindresorhus** [comment]
Closing for lack of activity.

**Pull request closed without merging**
