### PR TITLE
Replace all .then function with async/await

### LINKED ISSUE #149: Use `async/await`
Replace all the use of `.then()` with `await`.

Could also look into using other ES2015+ features.

### PR DESCRIPTION
**Pull request by FadySamirSadek**
Fixes #149

### CODE REVIEW

**Comment by Autre31415** [comment]
There's more examples of `.then()` calls in
- `extension/options.js`
- `extension/src/api.js`
- `extension/src/notifications-service.js`
- `extension/src/tabs-service.js`

**Comment by FadySamirSadek** [comment]
@Autre31415 I know I just wanted to push code as early as possible to get it reviewed to make sure I am on the right path , thanks 😉

**Comment by sindresorhus** [comment]
@FadySamirSadek You're on the right path. What you have looks good.

**Comment by sindresorhus** [comment]
Sorry @FadySamirSadek, this was indirectly fixed by #151.

**Comment by sindresorhus** [comment]
Happy to consider other contributions from you, though :D

**Pull request closed without merging**
