### PR TITLE
Remove redundant regex for token check

### LINKED ISSUE #248: Error: missing token (new token format)
After updating to 21.4.6 (Firefox) we can set the new token but it cannot be used due to this check:

https://github.com/sindresorhus/notifier-for-github/blob/c9c66fe81df2767eb8ec705cba3d3f066728583b/source/lib/api.js#L44-L46

### PR DESCRIPTION
**Pull request by RafaelKr**
fix #248

https://regex101.com/r/yMMKp9/1/

### CODE REVIEW

**Comment by fregante** [comment]
I think this check is redundant and should be removed. Invalid tokens are not saved

**Comment by RafaelKr** [comment]
cc @sindresorhus I can remove this check at all if you want?

Edit: I think it makes sense. Already removed it.

**Comment by fregante** [comment]
You might want to  keep it as a plain existence check. `if !token, throw`

**Comment by RafaelKr** [comment]
Updated. Thanks!

**Review by fregante — APPROVED** [review]

**Pull request merged**
