### PR TITLE
Remove myself from maintainers list

### PR DESCRIPTION
**Pull request by YurySolovyov**
I've stopped using the extension as part of the overall war on distractions :)
Thanks for a nice maintainer experience, it was great to work on this ext.

### CODE REVIEW

**Comment by ArnaudLigny** [comment]
Thanks a lot for your good job! 👍

**Comment by notlmn** [comment]
Thanks Yury, for maintaining this project for so long and also for guiding me when I started on it. I respect your decision. 🙂

**Comment by sindresorhus** [comment]
@YurySolovyov I really appreciate all you've done here. How about we just move your name to a `Former` subsection?

**Comment by YurySolovyov** [comment]
@sindresorhus done.

Edit: doh, master was updated, and I screwed up the merge :man_facepalming:

**Review by notlmn — APPROVED** [review]
Now it's up to @sindresorhus.

**Pull request merged**
